/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LowStockRouteImport } from './routes/low-stock'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RiskMonitorRouteImport } from './routes/risk-monitor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LowStockRoute = LowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMonitorRoute = RiskMonitorRouteImport.update({
  id: '/risk-monitor',
  path: '/risk-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/deliveries': typeof DeliveriesRoute
  '/intelligence': typeof IntelligenceRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/risk-monitor': typeof RiskMonitorRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/warehouses': typeof WarehousesRoute
  '/what-if': typeof WhatIfRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/deliveries': typeof DeliveriesRoute
  '/intelligence': typeof IntelligenceRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/risk-monitor': typeof RiskMonitorRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/warehouses': typeof WarehousesRoute
  '/what-if': typeof WhatIfRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adjustments': typeof AdjustmentsRoute
  '/deliveries': typeof DeliveriesRoute
  '/intelligence': typeof IntelligenceRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/low-stock': typeof LowStockRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/risk-monitor': typeof RiskMonitorRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/warehouses': typeof WarehousesRoute
  '/what-if': typeof WhatIfRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjustments'
    | '/deliveries'
    | '/intelligence'
    | '/ledger'
    | '/locations'
    | '/login'
    | '/low-stock'
    | '/products'
    | '/profile'
    | '/receipts'
    | '/risk-monitor'
    | '/settings'
    | '/transfers'
    | '/warehouses'
    | '/what-if'
    | '/products/$productId'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjustments'
    | '/deliveries'
    | '/intelligence'
    | '/ledger'
    | '/locations'
    | '/login'
    | '/low-stock'
    | '/profile'
    | '/receipts'
    | '/risk-monitor'
    | '/settings'
    | '/transfers'
    | '/warehouses'
    | '/what-if'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/adjustments'
    | '/deliveries'
    | '/intelligence'
    | '/ledger'
    | '/locations'
    | '/login'
    | '/low-stock'
    | '/products'
    | '/profile'
    | '/receipts'
    | '/risk-monitor'
    | '/settings'
    | '/transfers'
    | '/warehouses'
    | '/what-if'
    | '/products/$productId'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdjustmentsRoute: typeof AdjustmentsRoute
  DeliveriesRoute: typeof DeliveriesRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LedgerRoute: typeof LedgerRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  LowStockRoute: typeof LowStockRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RiskMonitorRoute: typeof RiskMonitorRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRoute
  WarehousesRoute: typeof WarehousesRoute
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-stock': {
      id: '/low-stock'
      path: '/low-stock'
      fullPath: '/low-stock'
      preLoaderRoute: typeof LowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-monitor': {
      id: '/risk-monitor'
      path: '/risk-monitor'
      fullPath: '/risk-monitor'
      preLoaderRoute: typeof RiskMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdjustmentsRoute: AdjustmentsRoute,
  DeliveriesRoute: DeliveriesRoute,
  IntelligenceRoute: IntelligenceRoute,
  LedgerRoute: LedgerRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  LowStockRoute: LowStockRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRoute,
  RiskMonitorRoute: RiskMonitorRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRoute,
  WarehousesRoute: WarehousesRoute,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
